### ISSUE TITLE
(Bug) Event Table Module Empty 

### ISSUE THREAD

**Issue by Werewing** [Tharylia/Blish-HUD-Module-Releases#1]
The Event Table stopped stocking/drawing events to the table and now only shows a small white vertical line when enabled.

Worked for about 20 minutes before this error started. Restarting and reinstalling then restarting did not fix the issue.

**Comment by Tharylia** [comment]
Hi there, you didn't accidentally set timespan to 0?
Had that happen to me as well when I searched for bugs.

If that is not the case, can you post a screenshot of the table and all your settings?

**Comment by Werewing** [comment]
It is not, I kept it at the default 120.
Between these screens you should be able to see all my settings. Is there a settings file I could use instead, though?

![BlishEventTableBug](https://user-images.githubusercontent.com/25409479/150697523-db8eb4d2-05ea-4aa1-9c93-fe61bd24966e.png)
![Settings2](https://user-images.githubusercontent.com/25409479/150697656-56e25848-e6e9-4beb-b92b-02c1570f5894.png)
![Settings1](https://user-images.githubusercontent.com/25409479/150697657-67329c6e-86f1-41a0-b2a5-6c5f7d5f305c.png)

**Comment by Werewing** [comment]
The blue box is just to block chat. The only part of the event table is the small white line right above the "s" Blish Hud.

**Comment by Tharylia** [comment]
Do you have any events enabled?
Tou can find them in the top left, the orange boss symbol.

**Comment by Tharylia** [comment]
If you got some events enabled, try to increase the time span or activate the filler events.
Maybe you only selected events which are spread far apart (like ley line anomaly or karka, tequatl,..)

**Comment by Werewing** [comment]
Figured it out. I confused the Event Table options with the Event and Meta Observer options. I turned all the options off on yours thinking I was turning off the options on that module.

**Comment by Tharylia** [comment]
Yeah there are likely more people who get confused which is which module.
But I'm glad you found the problem.

If you have any other problems or suggestions feel free to create a new issue.
